uploads = []
generated = []

[[outputs]]
id = "4jv_glfjKoTX-DlQdVXxv"
uri = "file://.local/outputs/PhotoShare-Hub.pptx"
type = "slides"
title = "PhotoShare Hub.pptx"

[[outputs]]
id = "-8mEKsnG-B5Jgs0GHH8jq"
uri = "file://docs/user-guide.pdf"
type = "pdf"
title = "User Guide (fixed)"

[[outputs]]
id = "NM2M5YMCQLCW1RWVYdvV7"
uri = "file://docs/admin-guide-import.pdf"
type = "pdf"
title = "Admin Guide — Import (fixed)"
